name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
      cargo install --force rustfmt
      cargo install --force clippy

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Check for format errors
      run: |
        if [ $? -ne 0 ]; then
          echo "rustfmt found format errors, failing the build."
          exit 1
        fi

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check for clippy warnings
      run: |
        if [ $? -ne 0 ]; then
          echo "clippy found warnings, failing the build."
          exit 1
        fi

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
